- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      application: eap-cluster-app
    name: eap-cluster-app
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: eap-cluster-app:latest
    source:
      dockerfile: |-
        FROM ${EAP_RUNTIME_IMAGE_NAME}
        COPY /server $JBOSS_HOME
        USER root
        RUN chown -R jboss:root $JBOSS_HOME && chmod -R ug+rwX $JBOSS_HOME
        USER jboss
        CMD $JBOSS_HOME/bin/openshift-launch.sh
      images:
      - from:
          kind: ImageStreamTag
          name: eap-cluster-app-build-artifacts:latest
        paths:
        - destinationDir: .
          sourcePath: /s2i-output/server/
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-eap74-openjdk11-runtime-openshift:7.4.0
          namespace: eap-cluster-demo
        imageOptimizationPolicy: SkipLayers
      type: Docker
    triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: eap-cluster-app-build-artifacts:latest
      type: ImageChange
    - type: ConfigChange
